### ISSUE TITLE
Split out Alpine Port to its own repository

### ISSUE THREAD

**Issue by karianna** [adoptium/jdk8u#11]
As we were unable to get the Alpine port into jdk8u upstream in a timely manner we should remove the Alpine port from the main and release branches and put it in its own branch.

**Comment by karianna** [comment]
I just checked all 3 branches (`dev`, `release`, `master`).

- `master` - I think we leave untouched
- `release` - IIRC we had two patches go into this branch (https://github.com/adoptium/jdk8u/pull/9 & https://github.com/adoptium/jdk8u/pull/10) so I think it's a case of reversing those out.
- `dev` - I'm never quite sure how patches get in here.

I'd recommend a new branch called `alpine` in terms of having a branch that holds the patch.

**Comment by jerboaa** [comment]
@gdams Going by https://github.com/adoptium/jdk8u/pull/12#issuecomment-1378489078 the plan is to use a separate repo? Should we reflect this in this issue?

**Comment by gdams** [comment]
@jerboaa updated

**Comment by jerboaa** [comment]
Thank you @gdams!
