### ISSUE TITLE
Backport Portola to jdk8u (for Alpine musl build support)

### ISSUE THREAD

**Issue by karianna** [adoptium/jdk8u#5]
We are taking the best of the Bellsoft and Azul patches to their jdk8u distributions (a big thank you to them!) and applying that here for testing with the Adoptium community before Bellsoft submits the patch to OpenJDK proper.

**Comment by llamahunter** [comment]
Is an alpine version of a jdk8 docker image now available? I wasn't able to find it listed on https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#supported-tags-and-respective-dockerfile-links

**Comment by karianna** [comment]
Not yet, this will be a January PSU release for the binary.  Will also look for the container release at DockerHub also (tests pending)
